---
- hosts: prod
  gather_facts: false
  vars:
    repo: "https://github.com/Mehd0ch/TP_FINAL.git"
    branch: "main"
    dest: "/opt/app/TP_FINAL"
    build_root: "{{ playbook_dir }}/.build"
  tasks:
    - name: Clone repo on runner (local)
      delegate_to: localhost
      git:
        repo: "{{ repo }}"
        dest: "{{ build_root }}/{{ inventory_hostname }}"
        version: "{{ branch }}"
        force: yes

    - name: Ensure dest dir exists inside container
      delegate_to: localhost
      command: docker exec {{ inventory_hostname }} mkdir -p {{ dest }}

    - name: Copy code into container
      delegate_to: localhost
      command: docker cp "{{ build_root }}/{{ inventory_hostname }}/." "{{ inventory_hostname }}:{{ dest }}/"
