name: CI/CD (docker-conn)

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible + Docker collection
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Mini check (optionnel)
        run: |
          files=$(git ls-files '*.py' || true)
          [ -z "$files" ] || python3 -m py_compile $files

      - name: Deploy DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          ansible-playbook -i ansible/inventory/dev.ini ansible/playbooks/deploy-dev.yml -vv

      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        run: |
          ansible-playbook -i ansible/inventory/prod.ini ansible/playbooks/deploy-prod.yml -vv
